import random

def guess_game (usr_inp):
    rand = random.randint(1,9)
    if usr_inp == rand:
        result = "\n***** Guessed the right number!! you rock!! *****"
    elif usr_inp > rand:
        result = "\n***** Guessed too high, Try again! *****"  
    elif usr_inp < rand:
        result = "\n***** Guessed too low, Try again! *****"

    Fin_result =result +"\n" + f"\nNumber generated by code : {rand}\n"

    return Fin_result


if __name__ == "__main__":
    try:
        while True:
            print("\n******************************************************************************************") 
            usr_inp = (input('Enter a number (1-9) to Play "Guess the number Game" (or) Type "quit" to exit the game..\n\nWaiting for user input : '))
            if usr_inp != "quit":
                print(guess_game(int(usr_inp)))
            else:
                print("\nWell Played! , Ciao Soon!!\n")   
                break 
    except ValueError:
        print (f"\nProvided input '{usr_inp}' is not valid , Try again!\n")
        
   